services:
    api:
        build: .
        ports:
            - '3000:3000'
        depends_on:
            - db
        env_file:
            - .env
    db:
        image: postgres:13
        env_file:
            - .env
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
    db_data:
